test: &default

  # Credentials for REST APIs
  client_id: AeaJs9QXqch2vZYFGYta9gxQ0cBuZww8b9-jvZnQEUD38_ffjKRF7ZJYGIJTPF-MxTlBNwQCrjX5VcTh
  client_secret: EHjyuTU0xKxjZ2enz1ahr2q-g10sha9ZUDdvYms-osKyiOjK01sMq9DVm-AVEzq_JtKYoSxWEGDvvOBq

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: alan.142@hotmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
